version: 2
jobs:
  test_node_8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  release:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_node_8
      - release:
          requires:
            - test_node_8